services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: bookstore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      MYSQL_DATABASE: onlinestore
      MYSQL_USER: ${MYSQL_USER:-bookstore}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
    ports:
      - "${MYSQL_PORT:-3307}:3306"  # 改为3307端口
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    networks:
      - bookstore_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD:-123456}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go Backend Service
  backend:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: bookstore_backend_go
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-8082}:8081"  # 改为8082端口
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456}
      - DATABASE_DBNAME=onlinestore
      - DATABASE_PORT=3306
      - GIN_MODE=release
    networks:
      - bookstore_network

  # Vue Frontend Service
  frontend:
    build:
      context: ./Sofeware_Demo
      dockerfile: Dockerfile
    container_name: bookstore_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    networks:
      - bookstore_network

volumes:
  mysql_data:

networks:
  bookstore_network:
    driver: bridge



