version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: bookstore_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-BookStore2024!}
      MYSQL_DATABASE: onlinestore
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-BookStore2024!}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookstore_network

  # Spring Boot后端
  backend:
    build: ./backend
    container_name: bookstore_backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/onlinestore?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-BookStore2024!}
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - bookstore_network

  # Vue前端
  frontend:
    build: ./Sofeware_Demo
    container_name: bookstore_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - bookstore_network

volumes:
  mysql_data:

networks:
  bookstore_network:
    driver: bridge 